/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 398e781c05ede31e9fb5fb48c7a0295d)
interface __BaseEnv_Env {
	VAPOR_API: DurableObjectNamespace<import("./src/index").VaporAPIContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "VaporAPIContainer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
