/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: e0f5d4e1fce8e002c8b7a120af200d70)
interface __BaseEnv_Env {
	GUIDE_PHOTOS: R2Bucket;
	DB: D1Database;
	VAPOR_API: DurableObjectNamespace<import("./src/index").VaporAPIContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "VaporAPIContainer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
